### ISSUE TITLE
Bundled punycode module is deprecated

### ISSUE THREAD

**Issue by djbrown** [postmanlabs/postman-url-encoder#89]
While reading the [Postman JavaScript reference](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-external-libraries) I discovered that Postman uses the deprecated `punycode` module.

https://nodejs.org/api/punycode.html:
> **The version of the punycode module bundled in Node.js is being deprecated.** In a future major version of Node.js this module will be removed. Users currently depending on the `punycode` module should switch to using the userland-provided [Punycode.js](https://github.com/bestiejs/punycode.js) module instead. For punycode-based URL encoding, see [`url.domainToASCII`](https://nodejs.org/api/url.html#url_url_domaintoascii_domain) or, more generally, the [WHATWG URL API](https://nodejs.org/api/url.html#url_the_whatwg_url_api).

It doesn't seem to be too much effort to fix, yet it has to be done across multiple affected repositories:
https://github.com/search?q=org%3Apostmanlabs+punycode&type=Code

**Comment by codenirvana** [comment]
Yes `punycode` library is available in Postman's script (pre-request and test) execution sandbox however it's not used while sending user's request.

I hear your concern but there are two primary reasons to not remove this from the sandbox:
1. It's added 5-6 years ago and removing this will break a lot of existing collections
2. It's compatible with browserify, it works on the Postman web

**Comment by djbrown** [comment]
@codenirvana my suggestion was not to remove it, but to switch to the proper punycode module

**Comment by codenirvana** [comment]
@djbrown Got it but, `domainToASCII` method has [native](https://github.com/nodejs/node/blob/v14.16.0/src/node_url.cc#L2263) dependencies which will not work with Browserify.

The `url` library available in the sandbox (Browserify built-in) is https://github.com/defunctzombie/node-url.
